translated_keys = {
    "DVD в США": "releaseDVDUsa",
    "актеры": 'actors',
    "бюджет": 'budget',
    "возраст": 'ageLimit',
    "время": 'duration',
    "год": 'year',
    # "директор фильма",
    "дубляж": 'dubbing',
    "жанр": 'genres',
    "зрители": 'people',
    "композитор": 'composers',
    "маркетинг": 'marketing',
    "монтаж": 'editors',
    "оператор": 'operators',
    "описание": 'descr',
    "ошибки": 'error',
    "премьера (РФ)": 'releaseRussia',
    "премьера (мир)": 'releaseWorld',
    "продюсер": 'producers',
    # "ре-релиз (РФ)": 'reReliase',
    "режиссер": 'directors',
    "рейтинг MPAA": 'rateMPAA',
    "релиз на Blu-ray": 'releaseBlueRay',
    "релиз на DVD": 'releaseDVD',
    "сборы в России": 'moneyRussia',
    "сборы в США": 'moneyUSA',
    "сборы в мире": 'moneyWorld',
    "слоган": 'slogan',
    "страна": 'countries',
    "сценарий": 'writers',
    "факты": 'facts',
    "художник": 'artDirectors',
    "цифровой релиз": 'digitRelease'
}
